# Generated by Django 6.1.1 on 2026-09-08 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profiles/avatars/')),
                ('is_kids', models.BooleanField(default=False)),
                ('language', models.CharField(choices=[('en', 'English'), ('ur', 'Urdu'), ('hi', 'Hindi'), ('es', 'Spanish'), ('fr', 'French'), ('ar', 'Arabic')], default='en', max_length=10)),
                ('maturity_level', models.CharField(choices=[('all', 'All Ages'), ('7+', '7+'), ('13+', '13+'), ('16+', '16+'), ('18+', '18+')], default='18+', max_length=10)),
                ('pin', models.CharField(blank=True, max_length=128, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'name'), name='unique_profile_name_per_user')],
            },
        ),
    ]
