# Generated by Django 6.1.1 on 2026-09-08 16:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='catalog/people/')),
                ('bio', models.TextField(blank=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('description', models.TextField()),
                ('poster', models.ImageField(blank=True, null=True, upload_to='catalog/posters/')),
                ('backdrop', models.ImageField(blank=True, null=True, upload_to='catalog/backdrops/')),
                ('trailer_url', models.URLField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('release_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes.')),
                ('maturity_rating', models.CharField(choices=[('all', 'All Ages'), ('7+', '7+'), ('13+', '13+'), ('16+', '16+'), ('18+', '18+')], default='18+', max_length=10)),
                ('language', models.CharField(choices=[('en', 'English'), ('ur', 'Urdu'), ('hi', 'Hindi'), ('es', 'Spanish'), ('fr', 'French'), ('ar', 'Arabic'), ('ko', 'Korean'), ('ja', 'Japanese'), ('other', 'Other')], default='en', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('view_count', models.PositiveBigIntegerField(default=0)),
                ('genres', models.ManyToManyField(blank=True, related_name='movies', to='catalog.genre')),
                ('cast', models.ManyToManyField(blank=True, related_name='movie_cast', to='catalog.person')),
                ('directors', models.ManyToManyField(blank=True, related_name='directed_movies', to='catalog.person')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TVShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('description', models.TextField()),
                ('poster', models.ImageField(blank=True, null=True, upload_to='catalog/shows/posters/')),
                ('backdrop', models.ImageField(blank=True, null=True, upload_to='catalog/shows/backdrops/')),
                ('trailer_url', models.URLField(blank=True)),
                ('release_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('maturity_rating', models.CharField(choices=[('all', 'All Ages'), ('7+', '7+'), ('13+', '13+'), ('16+', '16+'), ('18+', '18+')], default='18+', max_length=10)),
                ('language', models.CharField(choices=[('en', 'English'), ('ur', 'Urdu'), ('hi', 'Hindi'), ('es', 'Spanish'), ('fr', 'French'), ('ar', 'Arabic'), ('ko', 'Korean'), ('ja', 'Japanese'), ('other', 'Other')], default='en', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('view_count', models.PositiveBigIntegerField(default=0)),
                ('cast', models.ManyToManyField(blank=True, related_name='show_cast', to='catalog.person')),
                ('directors', models.ManyToManyField(blank=True, related_name='directed_shows', to='catalog.person')),
                ('genres', models.ManyToManyField(blank=True, related_name='tv_shows', to='catalog.genre')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('season_number', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='catalog/seasons/')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='catalog.tvshow')),
            ],
            options={
                'ordering': ['season_number'],
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('episode_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='catalog/episodes/')),
                ('video_url', models.URLField(blank=True)),
                ('trailer_url', models.URLField(blank=True)),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes.')),
                ('release_date', models.DateField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('view_count', models.PositiveBigIntegerField(default=0)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='catalog.season')),
            ],
            options={
                'ordering': ['episode_number'],
                'constraints': [models.UniqueConstraint(fields=('season', 'episode_number'), name='unique_episode_per_season')],
            },
        ),
        migrations.AddConstraint(
            model_name='season',
            constraint=models.UniqueConstraint(fields=('show', 'season_number'), name='unique_season_per_show'),
        ),
    ]
